var myFriendsage = [22, 23, 24];
var myfriendsmoney = [3, 200, 255, 50];
var myfriendsname = ['lebu', 'rabbi', 'shas', 'asif', 'mathamuta'];
var oddnumbers = [1, 3, 5, 7, 9];
var vowels = ['a', 'e', 'i', 'o', 'u'];
console.log(myfriendsname.length);
console.log(vowels.length);
console.log(oddnumbers.length);
console.log(myfriendsmoney.length);
console.log(myFriendsage.length);
